name: MacOS 13
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: true

env:
  GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
  
  NETDATA_TOKEN: ${{ secrets.NETDATA_TOKEN }}
  NETDATA_ROOM:  ${{ secrets.NETDATA_ROOM }} 
  NETDATA_URL:   ${{ secrets.NETDATA_URL }} 

jobs:
  build:
    runs-on: macos-13
    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Stage Environment
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - uses: actions/checkout@v2
        run: |
             chmod +x ./public/scripts/kickstart.sh \
             ./public/scripts/kickstart.sh          \
             echo "Hello Runner" >> echo.txt        \
        shell: zsh
